### ISSUE TITLE
How do I delete an entry based on value rather than timeshare range?

### ISSUE THREAD

**Issue by plunkinguitar** [attm2x/m2x-python#13]
I have been looking through streams.py and only could find the ability to delete values based on a timestamp, is this the only way to delete entries?

**Comment by fsaravia** [comment]
@plunkinguitar: Yes, that's the only way M2X supports for deleting values at the moment, feel free to post on our [Developer Forum](http://developerboards.att.lithium.com/t5/M2X-Data-Service/bd-p/M2X_Data_Service) for anything else related to the service
