### ISSUE TITLE
Feature: Add Support for Optional Params when Adding Device to a Distribution

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-python#27]
The [Add Device to an existing Distribution](https://m2x.att.com/developer/documentation/v2/distribution#Add-Device-to-an-existing-Distribution) endpoint provides parameters for further defining the Device attributes, however, the Distribution.add_device() method of the M2X Python client library does not support passing params.

Update this method to allow **params.

**Comment by omab** [comment]
Fixed by #31
